### ISSUE TITLE
Bower not working with 1.3.1 due to missing Control.Geocoder.js

### ISSUE THREAD

**Issue by BryanMorgan** [perliedman/leaflet-control-geocoder#100]
I think I understand the discrepancy between the way Leaflet does bower.json and the way it is set up here (per issue https://github.com/perliedman/leaflet-control-geocoder/issues/89).

The Leaflet releases (like https://github.com/Leaflet/Leaflet/releases/tag/v0.7.3) always include a `dist` directory that has the output from the build (`dist/leaflet.js`, `dist/leaflet-src.js`) in addition to the source files in git.

So an easy solution to solve #89 and to allow people to reference your awesome project through bower is simply to keep the source code exactly as-is, but when you push a release out, build the `dist` folder using browserify and the include that in the version archives. That way projects referencing this one through bower can use the built `Control.Geocoder.js` that is missing from the 1.3.0 and 1.3.1 releases.

I'd be happy to build another 1.3.1a or 1.3.2 release with the `dist` folder if that helps.

**Comment by perliedman** [comment]
@BryanMorgan interestnig. Any help with fixing this would be awesome!

**Comment by derwaldgeist** [comment]
+1

This does not work with bower at the moment. Bower won't do an automatic build, it requires compiled files to be directly available. Your bower.json file is not valid, as it points to an unavailable file.

**Comment by perliedman** [comment]
@derwaldgeist I don't personally use Bower, and know very little about it. The current setup has been contributed by other developers.

As noted above, help in this area is very welcome. I maintain this in my spare time, and will not personally spend any time on fixing Bower issues.

**Comment by derwaldgeist** [comment]
Thanks for your feedback. In this case, I think it would be best to completely remove bower support, as it is not working. Bower relies on having the files in a dist-like format, i.e. without any building steps. If this is not possible or you do not want to include the dist files, the only option is to drop bower.

**Comment by perliedman** [comment]
`dist` files are included in the repository for tagged versions, just like Leaflet does, from version 1.3.4.

Please check if that works for you!

**Comment by DDroll** [comment]
Nope.. 'dist' should be present in main block pathes, lik this main : { dist/ControlBlala.js}. After this change it works normally.

**Comment by perliedman** [comment]
@DDroll please submit a PR if you have a fix, I don't use Bower and don't have any time to put into supporting it.
