### ISSUE TITLE
Can't initializing controller, throw the exception: "Nominatim is not a constructor"

### ISSUE THREAD

**Issue by p4535992** [perliedman/leaflet-control-geocoder#101]
Hi, sorry to trouble you, i'm want to use your plugin, but i have encountered some really issue.
I have posted a question on stackoverflow with all details and a live example on jsfiddle:
http://stackoverflow.com/questions/33476365/leaflet-control-gecoder-exception-nominatim-is-not-a-constructor

if you had time to look at it, I would be very grateful . Ty in advance.

**Comment by perliedman** [comment]
Hm, I'm guessing you're using an old version, the problem you're seeing was fixed here: https://github.com/perliedman/leaflet-control-geocoder/commit/423610e7f63fd381357f44b2bc9853bd919c3e88

Upgrade to 1.3.1, and this should be fixed, as far as I can tell.
