### ISSUE TITLE
Geocoder working on browser but not on mobile

### ISSUE THREAD

**Issue by MrVico** [perliedman/leaflet-control-geocoder#108]
I'm using the leaflet geocoder in my mobile app (ionic).
When I test on the browser it works fine, I can search a city and it will locate it for me, but when I search on my mobile phone it just keeps searching and searching without ever finding anything, the searchbox is shown but it doesn't work. 
What can be the problem?

**Comment by perliedman** [comment]
Hi there,
might it be the same issue as this one: https://github.com/perliedman/leaflet-routing-machine/issues/160 ?

That is, Ionic doesn't support protocol relative URLs. You could try overriding the `serviceUrl` option with something that uses `http` or `https` explicitly.

**Comment by MrVico** [comment]
Hi, sorry, I can't seem to find the leaflet-routing-machine.js he is talking about, do I need to download it apart from the Geocoder?
I'm a newb =(

**Comment by MrVico** [comment]
I'm having quite some trouble locating the line he is talking about, since my file has only two lines and is extended in width...

**Comment by MrVico** [comment]
Should I add http: in front of every serviceUrl that starts with // in my Control.Geocoder.js ?

**Comment by perliedman** [comment]
@MrVico you don't need to change the source, you can pass `serviceUrl` as an option when you create the geocoder.

**Comment by elsasantos** [comment]
Hi,
I have the serviceUrl option, but in the mobile the "Enter" key does nothing. 
How can I show the results as I write? I apply the suggestMinLength option but it doesn't do anything.
Every help is welcome.
