### ISSUE TITLE
Mapzen geocoder not searching

### ISSUE THREAD

**Issue by KentJacobs** [perliedman/leaflet-control-geocoder#110]
I'm having some problems preforming a search using the Mapzen provider. I have other providers (Nominatim, Photon, etc.) working without any problems in my code.

Here's my index.js file that I'm using for my html file.

http://pastebin.com/qnmvVeEk

Here's my Control.Geocoder.js file where I am editing the URLs.

http://pastebin.com/90nPgAVU

**Comment by KentJacobs** [comment]
When I attempt a search in Chrome and run a error log report I get:

```Uncaught TypeError: Cannot read property 'geocode' of undefined...
module.exports.class.L.Control.extend._geocode@	Control.Geocoder.js:118
t.(anonymous function).s	@	leaflet.js:8```

**Comment by KentJacobs** [comment]
So it appears to be querying using the search.mapzen.com/v1 URL now.

I changed ```'Pelias': L.Control.Geocoder.Mapzen('apiKey')``` to ```'Pelias': L.Control.Geocoder.mapzen('apiKey')```. Apparently that made all the difference.

**Comment by perliedman** [comment]
Yes, this attempts to follow Leaflet's conventions for factories versus class constructors: `L.Control.Geocoder.Mapzen` is a constructor, and should be used with `new`, like: `new L.Control.Geocoder.Mapzen('apiKey')`, but `L.Control.Geocoder.mapzen` is a factory and should be called without `new`.
