### ISSUE TITLE
Address detail color problem

### ISSUE THREAD

**Issue by fmiguelroliveira** [perliedman/leaflet-control-geocoder#113]
Hello Per,

I'm having a problem with the color of address in your plugin. When i do a search, it returns me possible addresses and after choosing one, it popups a ballon in map with the address(white) and region(gray).

The problem is that the popup ballon is, in general white, and if you define a site default font as white, the address although present is not visible with white ballon background.

This is what appears (example):
<div class="leaflet-popup-content" style="width: 79px;"><span class=""> Porto  </span><br><span class="leaflet-control-geocoder-address-context">North Portugal</span></div>

After looking at css and js i've noticed that:

CSS
.leaflet-control-geocoder-address-detail {
} /*empty*/

JS at line 662:
if (a.city || a.town || a.village) {
	parts.push('<span class="' + (parts.length > 0 ? 'leaflet-control-geocoder-address-detail' : '') +
						'">{postcode} {city} {town} {village}</span>');
}

I was wondering if it was a good idea to change this in order to have a default color for address-detail, like address-context?

Or i would be glad if you could tell me alternatives in order to avoid edit the code.

Thanks in advance and congrats for this excelent plugin!

Miguel

**Comment by perliedman** [comment]
Hi,

You can override the CSS like you want if you add more CSS after the geocoder's.

The popup's white color comes from Leaflet's default, so if you like to have a white font, you might want to restyle Leaflet's popup accordingly.
