### ISSUE TITLE
Pelias reverse geocoding

### ISSUE THREAD

**Issue by curiousc0w** [perliedman/leaflet-control-geocoder#115]
According to Pelias documentation, it should handle reverse geocoding like Nominatim. Although on my web page Pelias continues to search as text. Here's the console response in the web console.

eg. ```http:// <IP address> /v1/search?text=45.42526%2C%20-75.70001```

My Control.Geocoder.js is the same same yours but just different service URLs pointing to my server.

**Comment by perliedman** [comment]
Hi and sorry for taking quite a while to respond to this.

I can't replicate this problem when using the Mapzen/Pelias geocoder in the demo. If this is still a problem, could you provide the code you're using?

This is what the URLs look like for me:

```
http://search.mapzen.com/v1/reverse?api_key=<key>&point.lat=57.79794388498275&point.lon=11.997070312499998
```

**Comment by curiousc0w** [comment]
I have a similar Leaflet page to yours with Google, Nominatim and Pelias geocoders. Nominatim and Pelias are both local instances, so I am not using the Pelias geocoder over the web and no api key is needed.

Here's what happens when I try a coordinate.

![Image](https://i.imgsafe.org/9460ccb.png)

This is the request in the browser console.

```http://localhost:3100/v1/search?text=45.425%2C%20-75.700```

Here's a gist of my code.

https://gist.github.com/curiousc0w/5e4db80f5b55f9262615#file-controlgeocoder-js

https://gist.github.com/curiousc0w/24f0d44b5cecd69c3ea0#file-index-js

**Comment by perliedman** [comment]
I think you have misunderstood how the reverse geocoding works. It's not for entering a coordinate in the search field, it's a special function you call on the geocoder instance you use. You need to add your own handler to call the `reverse` method; you can look at the demo for how to do it.. The search field will _always_ use the `query` method.
