### ISSUE TITLE
Nominatim Geocoder appears to ignore the countrycodes

### ISSUE THREAD

**Issue by JamesMilnerUK** [perliedman/leaflet-control-geocoder#117]
Hello! It appears the Nominatum geocoder appears to be ignoring requested countries:

``` javascript
L.control.locate().addTo(map);
    var geocoder = new L.Control.geocoder({
        geocoder: L.Control.Geocoder.Nominatim({
            geocodingQueryParams: { countrycodes: 'gb'}
        })
    }).addTo(map);
```

But results appear to be global in nature:

![screen shot 2016-02-03 at 17 37 29](https://cloud.githubusercontent.com/assets/8822075/12790992/e806f4dc-ca9c-11e5-85d7-ab05b568cfa4.png)

Are there any known work arounds? Happy to dig around the code etc.

**Comment by perliedman** [comment]
Please use your browser's developer tools to check the URL used when querying the Nominatim service. Does the URL include the `countrycodes` query parameter? If it does, it would indicate a problem with the Nominatim service rather than in Leaflet Control Geocoder. Otherwise, I guess we would need to check that parameters are passed on correctly to the URL.

**Comment by perliedman** [comment]
Closing for now until we have more information.

**Comment by WilliamWalker** [comment]
I'm having the same issue.  

```
                var geocoder = L.Control.geocoder({
                    defaultMarkGeocode: false,
                    geocodingQueryParams: {
                        countrycodes: 'jp' //japan
                    }
                })
```
This, however, results in the following request url:
https://nominatim.openstreetmap.org/search?q=tokyo tower&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_1

**Comment by slead** [comment]
I can confirm that this behaviour also occurs for me with the Nominatim geocoder:

![leaflet geocoder](https://cloud.githubusercontent.com/assets/133596/21169698/b179c548-c212-11e6-8ec6-55fe657d06c3.PNG)

The resulting query URL does not contain the `countrycodes` parameter, and therefore contains American results:

http://nominatim.openstreetmap.org/search/?q=richmond&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0

If I manually modify the query to include the `countrycodes` parameter, the expected Australian results are returned;

http://nominatim.openstreetmap.org/search/?q=richmond&countrycodes=au&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0

PS thanks for writing such a useful tool

**Comment by perliedman** [comment]
Hi @slead,
good to hear you're finding the plugin useful! Which version of Leaflet Control Geocoder are you running? What does your code look like?

I've tested this with the following code:

```javascript
var geocoder = L.Control.Geocoder.nominatim({
	geocodingQueryParams: {
		countrycodes: 'au'
	}
}),
control = L.Control.geocoder({
	geocoder: geocoder
}).addTo(map),
```

With this setup, running latest version of the plugin, searching for "Perth" I get this URL in Chrome devtools' network tab:

https://nominatim.openstreetmap.org/search?q=perth&limit=5&format=json&addressdetails=1&countrycodes=au&json_callback=_l_geocoder_0

So it appears to work. Anything different in your setup that could explain this?

**Comment by slead** [comment]
When I downloaded the 1.5.4 version from https://github.com/perliedman/leaflet-control-geocoder/releases it works as expected.

https://nominatim.openstreetmap.org/search?q=richmond&limit=5&format=json&addressdetails=1&countrycodes=au&json_callback=_l_geocoder_2

Thanks for the fast response, and keep up the awesome work!

**Comment by perliedman** [comment]
Great to hear! Thanks.
