### ISSUE TITLE
Multiple markers

### ISSUE THREAD

**Issue by curiousc0w** [perliedman/leaflet-control-geocoder#118]
I was wondering if there was a feature to have separate markers for each of the geocoders. Ie, a blue marker for Nominatim, red for Photon, green for Google, etc... I know how to implement a new marker there is just some trouble with having that marker represent one geocoding option.

**Comment by perliedman** [comment]
Nothing built in, but it should be pretty easy to implement by overriding the `markGeocode` method: you can check `this.options.geocoder` to determine which geocoder is currently active, and create the approriate marker depending on it.

Does that answer your question?

**Comment by curiousc0w** [comment]
@perliedman 

Somewhat, yes. I am fairly new to JS so this will take some playing around.

**Comment by curiousc0w** [comment]
I tested out changing the colour of the marker on a Leaflet page with just Nominatim. I will work on this with the control geocoder Leaflet page (Nominatim, Pelias, Google, etc...)

```html
<!DOCTYPE html>
<html>
<head>
	<title>Leaflet Control Geocoder</title>

  <meta name='viewport' content='width=device-width, user-scalable=no initial-scale=1, maximum-scale=1'>

	<link rel="stylesheet" href="leaflet.css" />
	<link rel="stylesheet" href="Control.Geocoder.css" />

	<script src="leaflet.js"></script>
	<script src="Control.Geocoder.js"></script>
	<style type="text/css">
		body {
			margin: 0;
		}
		#map {
			position: absolute;
			width: 100%;
			height: 100%;
		}
	</style>
</head>
<body>
	<div id="map"></div>

	<script type="text/javascript">

	// Custom map icon for toolbar
	var LeafIcon = L.Icon.Default.extend({
			options: {
				iconUrl: 'images/marker-icon-red.png',
			}
	});

	var redIcon = new LeafIcon;

	var map = L.map('map').setView([0, 0], 2);
		L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
		}).addTo(map);

		var geocoder = L.Control.geocoder().addTo(map);

		geocoder.markGeocode = function(result) {
		    var markerLocation = new L.latLng(result.center)
			L.marker(markerLocation, {
				icon: redIcon
					})
			.addTo(map);
		};
	</script>
</body>
</html>
```
