### ISSUE TITLE
Support for multiple geocoders

### ISSUE THREAD

**Issue by chriscalip** [perliedman/leaflet-control-geocoder#121]
Who wants it? Can we have it?

I am trying to stitch together results from different geocoders (even custom ones).

**Comment by perliedman** [comment]
I imagine it would be fairly straight forward to make a geocoder that queries a number of other geocoders and returns their results.

Two things to consider is that querying a geocoder is asynchronous, so you would have to wait for all geocoders to finish before the complete result. Perhaps not so straight forward is also how to _order_ the results from the geocoders: which result is more important than the other?

Feel free to submit a pull request if you implement this! Having said that, it's not something I will implement myself at this point.

**Comment by chriscalip** [comment]
You are right about the difficulty of managing multiple asynchronous request. Fortunately on my project my search index is locally available. The target search-index json arrays are already present in the html page when the map was painted. I was doing a https://github.com/krisk/Fuse Fuse search on an array of objects then add results to the geocoder results.
I have a prototype working where i call the locally available geocoder search first then call the remote geocoder next. My project budget is not big enough to develop a rigorous patch to contribute.
