### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by odbayar** [perliedman/leaflet-control-geocoder#124]
It fails on {postinstall: "sh ./scripts/build.sh"} as I don't have sh on my Windows box.

**Comment by perliedman** [comment]
Yeah, sorry about that.

That script can probably be turned into an NPM script. A PR to fix would be welcome.

**Comment by odbayar** [comment]
Sorry, I don't know anything about publishing to npm or bower, so I will probably just end up making it more broken.

But can't "postinstall" be "prepublish"?

**Comment by DominicFath** [comment]
@odbayar I had the same issue. I resolved it by running the npm install command in the terminal emulator which came packaged with my git bash installation called MinGW-64. https://mingw-w64.org/doku.php

hope that helps.
 @perliedman maybe something worth mentioning under Usage ?
