### ISSUE TITLE
Error with leaflet v1.0.0-beta.2

### ISSUE THREAD

**Issue by jcoupey** [perliedman/leaflet-control-geocoder#126]
Maybe you wish to stick with leaflet v0.7.3 until the v1 release but FWIW I'm reporting this error occurring with leaflet v1.0.0-beta.2. Tested with the v1.4.0 `demo/index.html`, replacing the cdn links for leaflet by `http://cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet*`.

When submitting the form in the geocoder control, I'm getting a `TypeError: location is undefined` in the console, pointing at `Control.Geocoder.js` on line 870.
That's inside the reverse function for the nominatim geocoder, which seems odd to me because only a direct search query is performed here.

**Comment by perliedman** [comment]
Thanks for reporting, yes I should get around to testing with Leaflet 1.0, should hopefully only need minor modifications.

**Comment by jcoupey** [comment]
Except this console output, everything has been running smoothly for me with v1.0.0-beta.2 (only used nominatim so far though).
The mentioned error on submit does not actually stop the geocoding process so everything is perfect if the console is closed. ;-)

**Comment by perliedman** [comment]
Leaflet 1.0 has a new handler for the return key, and a missing `preventDefault` in the control caused this to fire.

Thanks for catching this and reporting!
