### ISSUE TITLE
 Extrapolate the contry name and language of the address returned

### ISSUE THREAD

**Issue by tbrcrl** [perliedman/leaflet-control-geocoder#129]
Hi, I am using the geocoder to localize a point on a map and I have two questions

1. Extrapolate the contry name
I would like to write the corresponding country name in a text box using the Nominatim service and the htmlTemplate option (L.Control.Geocoder.Nominatim(options)). I suppose this is the right way to do the job.
Somebody has an example of code using the htmlTemplate option or another appropriate option to extrapolate the country name and write it in a separate text box?
Here below the code that I am currently using and that works fine.

```javascript
var map = L.map('map').locate({setView: true, maxZoom: 6}),
geocoder = L.Control.Geocoder.nominatim(),
control = L.Control.geocoder({
  geocoder: geocoder, placeholder: "Search on map", errorMessage: "No matching results found"
}).addTo(map),
marker;
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
map.on('click', function(e) {
  geocoder.reverse(e.latlng, map.options.crs.scale(map.getZoom()), function(results) {
    var r = results[0];
    if (r) {
      if (marker) {
        marker.
          setLatLng(r.center).
          setPopupContent(r.html || r.name).
          openPopup();
      } else {
        marker = L.marker(r.center).bindPopup(r.name).addTo(map).openPopup();
      }
    }
  })
})
```
![extrapolate-country-name](https://cloud.githubusercontent.com/assets/16580030/15386529/9f6717d4-1da8-11e6-9ca8-b348991b8e79.png)

2. Geocoder address language
I see that the language of the address returned by the geocoder is related to the browser language. Is there a way to lock the address language to, for example, English?
Thanks

**Comment by perliedman** [comment]
The  response from the geocoder includes `properties`, that will contain the the attributes returned directly from Nominatim. It includes the country as a separate string, that you can use.

Regarding language, there's a URL query parameter for Nominatim called [`accept-language`](http://wiki.openstreetmap.org/wiki/Nominatim#Parameters) that I think you can use for this. Put it in the geocoder's `geocodingQueryParams` and/or `reverseQueryParams`.
