### ISSUE TITLE
Keyboard ok but Mouse click nook

### ISSUE THREAD

**Issue by SilentT-FR** [perliedman/leaflet-control-geocoder#130]
i have fork the master and i have remove all geocoder except bing for my use and remove some lines for reduce network usage.

When i click on the result nothing do , but when i use the keyboard all ok,
Release 1.4.0 all geocoder OK
Master only Bings NoOK

**Comment by perliedman** [comment]
Does it work without your changes?

It's close to impossible for me to debug this when you've made changes that I can't see - also note that I can't offer free support for changes you made.

**Comment by SilentT-FR** [comment]
Master original no modify work well ....

you can see the unique modification have take https://github.com/SilentT-FR/leaflet-control-geocoder/commit/505bf5cd0df7e0a4d1b3f4fb449d2151bccaf4ed

**Comment by perliedman** [comment]
Ok.

Can you check your JavaScript console for errors? There might be some implicit dependency between the geocoders, and this breaks when you remove the others, but hard to tell without seeing the error messages.

Bonus points if you put a running example somewhere to make it easier investigate.

**Comment by SilentT-FR** [comment]
no error, :/ i upload on running test codepen http://codepen.io/anon/pen/KMPoEK

**Comment by perliedman** [comment]
Ok, I think I've found the issue.

For some reason, the `blur` event fires before the `click` listener in your example, but not in the main example. The workaround is to add this line in `Control.Geocoder.js` at line 196:

```
L.DomEvent.addListener(li, 'mousedown', L.DomEvent.preventDefault);
```

Not sure why only you experience this, though.

**Comment by SilentT-FR** [comment]
Yes when i mouse down, the result disappear, but with this modification when i mouse down the result rest

**Comment by perliedman** [comment]
Closing this since the code has been reworked many times since this was opened. In particular, the listener in question is now added through this line:

```
      L.DomEvent.addListener(li, 'mousedown touchstart', mouseDownHandler, this);
```

Which should have resolved this.
