### ISSUE TITLE
OLC in  the new format

### ISSUE THREAD

**Issue by davidpiesse** [perliedman/leaflet-control-geocoder#132]
Per,
I want to add an Google Open Location Code (OLC) geocoder to this project but it needs a reference / copy of the OLC code. I Could copy it into the src/geocoders/olc.js file but ideally we could use the actual file via a cdn / github ref.
[https://github.com/google/open-location-code](https://github.com/google/open-location-code)

Any suggestion as to what is best?

Otherwise I will go down the route of copying it into the olc.js file (23kb)

D

**Comment by simon04** [comment]
You could specify `open-location-code` as an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies). Bundling it with the library unnecessarily bloats the resulting library size, even for users not wanting to use OLC.

**Comment by davidpiesse** [comment]
Agree. 
This would be the best route, or a specific plugin dependency, although code is very minimal
