### ISSUE TITLE
can't use .on('markgeocode', function(e) {...}

### ISSUE THREAD

**Issue by yureckey** [perliedman/leaflet-control-geocoder#134]
Is something broke in builds or simply the doc for unreleased yet version?
There is no code
```
if (this.options.defaultMarkGeocode) {
				this.on('markgeocode', this.markGeocode, this);
			}
```
in dist script

**Comment by perliedman** [comment]
Yes, no version had yet been released.

I've published version 1.5.1 which, among other things, includes the new event system.

Thanks for bringing this to my attention!
