### ISSUE TITLE
installing v1.5.1 from NPM doesn't build dist

### ISSUE THREAD

**Issue by ChristianMMacy** [perliedman/leaflet-control-geocoder#136]
I just tried installing v1.5.1 from NPM and the build script fails if es3ify isn't installed manually.

Installing es3ify manually fixes this but since the build process won't work without it (and leave you with an empty Control.Geocoder.js) I thought I'd call it out.

I hope this is helpful ... is there additional information I can provide that would help figure out what's going on? I see es3ify listed in the dev dependencies so I'm not sure why it wouldn't have installed or thrown a warning.

**Comment by perliedman** [comment]
Hm, that's super weird, since es3ify is listed as a devDependency... I'll try to look at this.

Which NPM version are you runnning?

**Comment by ChristianMMacy** [comment]
Hmm - that might be why. I'm on 3.8.3. I can try again with 2.15.5. I totally forgot that I'd installed node 5.10 :-/

**Comment by perliedman** [comment]
It appears I have misunderstood devDependencies, and should have included es3ify as well as browserify in dependencies instead. Will fix.

**Comment by derwaldgeist** [comment]
Please don't add `browserify` as a dependency. This might break build systems in apps that are already using it. For instance, MeteorJS would import browserify more than once in this case. Instead, add it as a peer dependency. I'm also asking myself why you actually need this as a dependency? IMHO, the dist should not require browserify, it should be used for build purposes only.

**Comment by perliedman** [comment]
@derwaldgeist I think you're right. The issue exists, but mostly since we build the `dist` on install, which isn't necessarily what you want if you consume the plugin as a CommonJS module.

**Comment by simon04** [comment]
I think this has been resolved in 7ab1d99cf383179700208510c8198c5b499df9ce since the `postinstall` script is gone and NPM packages contain the `dist/` directory.
