### ISSUE TITLE
Custom Geocoder

### ISSUE THREAD

**Issue by JoshKeegan** [perliedman/leaflet-control-geocoder#137]
Hi,
Is it possible to add a custom geocoder without editing the source?

I'd like to add a geocoder that uses our internal postcode lookup system, so it isn't a geocoder that would be of any use to contribute back to this project.
I'd prefer it if I didn't have to edit any of the existing source code for this project, that way upgrading to new releases would still be a simple matter of copying over the new files.
Is that possible?
Thanks,
Josh

**Comment by perliedman** [comment]
Yes, sure. You just pass the instance of your geocoder to the `geocoder` option of the control. Something like:

```js
var geocoder = ...;
var control = L.Control.geocoder({
    geocoder: myGeocoder
});
```

**Comment by JoshKeegan** [comment]
Thanks :)

**Comment by JoshKeegan** [comment]
Hi again,
As a follow up to this, I'd like to be able to control the HTML that gets displayed for each result. 
I see in https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/geocoders/nominatim.js that this is done by options.htmlTemplate, but when I pass that in as:
```js
L.Control.geocoder(
{
  geocode: ...,
  options:
  {
    htmlTemplate: ...
  }
}).addTo(map);
```
it doesn't appear to be being called.
Is there any way of doing this?
Thanks again,
Josh

**Comment by JoshKeegan** [comment]
Sorry, I've just seen that htmlTemplate actually gets called from within the geocode function, so I can of course supply my own :)

**Comment by perliedman** [comment]
Exactly! The HTML functionality is unfortunately specific for each geocoder.
