### ISSUE TITLE
which one is 'the real thing' ???

### ISSUE THREAD

**Issue by COLABORATI** [perliedman/leaflet-control-geocoder#139]
Hi, sorry for that stupid outsider question, but which one is 'the real one'? Your repo? The one this was forked from? Or the one from [vladimirbuskin](https://github.com/vladimirbuskin/leaflet-control-geocoder)? I am confused. I can not dive into the diffs, I just would like to know which one would be good to use right now? Thank you very much for your attention!

**Comment by perliedman** [comment]
I like to imagine this is the "real thing". At least it's the one linked from Leaflet's plugin page.

It's based on @sa3m's geocoder, but the code bases have diverged significantly over the years, and at least last time I checked, there hasn't been so many changes from him.

**Comment by COLABORATI** [comment]
Are you interested in merging the changes of vladimir? Or will his branch exist as a separate one? Are you communicating about this? Thanks again! (Trying to understand why the forks).
