### ISSUE TITLE
How to get value from geocoder input

### ISSUE THREAD

**Issue by samcorcos** [perliedman/leaflet-control-geocoder#141]
Thanks for putting this together :) 

I'm looking to grab the input value of the Google geocoder so I can track what users are searching for. I don't see an easy way to do this from the documentation or from my quick glance through the source code.

Is there any built-in way to do this? Some sort of callback on change/submit? 

Or is this something I'd have to fork the repo to implement? If so, is it worth a PR?

**Comment by perliedman** [comment]
Hi, this sounds like a nice addition!

The control currently fires a `startgeocode` and `startsuggest` event when a query is submitted, but it does not include the actual query in the event data. It would be simple addition, look here: https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/control.js#L138

It would of course be desirable to include the same information in the `finishgeocode`/`finishsuggest` event as well (a couple of lines below).

A PR would be very welcome!
