### ISSUE TITLE
missing dist from latest commit

### ISSUE THREAD

**Issue by tomay** [perliedman/leaflet-control-geocoder#147]
Hello, dist/ seems to be missing from the latest build. Would you mind adding it? I did try to build it myself, but there are many dependencies that I couldn't sort out. 

I also tried including the source files from the demo, but this appears to be a much older version. 

thank you!

**Comment by perliedman** [comment]
The built dist files are only included on the release tag, so check the tagged version: https://github.com/perliedman/leaflet-control-geocoder/tree/v1.5.3/dist
