### ISSUE TITLE
L.Control.Geocoder undefined

### ISSUE THREAD

**Issue by nthhtn** [perliedman/leaflet-control-geocoder#149]
I'm writing in Java, my `jsp` file already includes `leaflet` and `Geocoder`. But when I try to use any API function, it always throws error `property x is not a function`. I try to `console.log(L.Control.Geocoder)` and it always returns `undefined`

Much to this impossibility, I check the browser, HTML document does get files I included

**Comment by perliedman** [comment]
Hard to tell without seeing the running code, but I would check the browser console for any error messages. If you check [the demo](https://github.com/perliedman/leaflet-control-geocoder/blob/master/demo/index.html), it does more or less exactly what you describe, so it definitely works.

**Comment by benscott** [comment]
Not sure if this is the same issue, but I was also getting undefined errors until I correctly assigned Leaflet to variable L before requiring Geocoder. 

Changing this:
```
    require('leaflet');
    require('leaflet-control-geocoder');
```

To:
```
    var L = require('leaflet');
    require('leaflet-control-geocoder');
```
fixed it for me.

**Comment by nthhtn** [comment]
I've found the solution. It is because I require `leaflet-control-geocoder` and far below I require `leaflet-src` and some other plugins once again, causing this error
