### ISSUE TITLE
Webpack warning

### ISSUE THREAD

**Issue by GuillaumeAmat** [perliedman/leaflet-control-geocoder#150]
When building a web app with `leaflet-control-geocoder@1.5.3`, Webpack throws the following warning:

```
WARNING in ../~/leaflet-control-geocoder/dist/Control.Geocoder.js
Critical dependencies:
1:495-502 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ../~/leaflet-control-geocoder/dist/Control.Geocoder.js 1:495-502
```

The module is imported by:
``` javascript
import leafletControlGeocoder from 'leaflet-control-geocoder';
```

**Comment by perliedman** [comment]
Yep, from 1.5.3 the main file is actually the built file. I'll consider reverting this if it means trouble.

**Comment by GuillaumeAmat** [comment]
> I'll consider reverting this if it means trouble.

I'm not sure about what you meant. You will revert or I need to import the source file?

**Comment by perliedman** [comment]
I mean that _I_ will consider reverting to the old way, linking to the source file and letting each user build the plugin themselves, in a future version, if the current method of linking directly to the built file is a problem for users.

For now, you can either accept the warning or import the source file.

**Comment by GuillaumeAmat** [comment]
Ok thanks
