### ISSUE TITLE
Update Leaflet dependency

### ISSUE THREAD

**Issue by Rudloff** [perliedman/leaflet-control-geocoder#152]
Hello,

This plugin still requires Leaflet 0.7 in bower.json although it seems to work correctly with Leaflet 1.0.
Would it be possible to update the depdendency in order to avoid Bower warnings?

**Comment by perliedman** [comment]
Hi! I've dropped the dependency on Leaflet, and you're responsible to see to that it's loaded yourself. Unfortunately, I forgot do to this for Bower, since I don't use it myself. I've updated and released 1.5.4 to reflect this change.
