### ISSUE TITLE
Include/return extra data from geocoder used

### ISSUE THREAD

**Issue by nomoregrapes** [perliedman/leaflet-control-geocoder#156]
Is it possible to make use of the extra data returned by some geocoders?

For example, Nominatim returns: a polygon for results that are areas; the OpenStreetMap object id; and some OpenStreetMap tags (name, alt_name, type, etc). E.g. https://nominatim.openstreetmap.org/details.php?place_id=157757266

**Comment by perliedman** [comment]
It depends on the specific geocoder implementation, but for Nominatim you can access the original response via the result's `properties`: https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/geocoders/nominatim.js#L55
