### ISSUE TITLE
this.options.geocoder[mode] is not a function (Version Problems?)

### ISSUE THREAD

**Issue by alexkleinwaechter** [perliedman/leaflet-control-geocoder#157]
I have a problem that drives me crazy. Your code works as expected but if I press the Search Icon I get the above error. Submitting the search with Enter works. I use leaflet 0.7.7. and your module in version 1.5.4

![image](https://cloud.githubusercontent.com/assets/24670532/21347449/eaf5766a-c6a8-11e6-9650-7a0463c7c45f.png)

![image](https://cloud.githubusercontent.com/assets/24670532/21347476/06737a7c-c6a9-11e6-9069-c2ae33e6f98a.png)

Do have version a possible version conflict? Do I need a higher leaflet version?

Best Alex!

**Comment by perliedman** [comment]
Hi there,
what does your setup look like? From checking up the [relevant lines in the source](https://github.com/perliedman/leaflet-control-geocoder/blob/v1.5.4/dist/Control.Geocoder.js#L80) it looks like your geocoder doesn't have the `geocode` method, which does seem a bit weird.

**Comment by matthewhampton** [comment]
I'm seeing the same thing here... I'm using webpack - not sure if that could have anything to do with it?

**Comment by perliedman** [comment]
@matthewhampton the `suggest` mode isn't supported by all geocoders, so the error in itself makes sense. The question is rather how the `_geocode` was called in suggest mode, even though it isn't supported. Please check one level up the stack trace and see how it's being called.

Also, a running example of this issue would make it a lot easier to debug.

**Comment by alexkleinwaechter** [comment]
Hey,
thanks for your hint with the suggest mode. When I click the Search Symbol the mouse event is given as a parameter to the geocoder:
![image](https://cloud.githubusercontent.com/assets/24670532/21426884/b595de38-c851-11e6-9c03-cf4e9e937477.png)

In the geocoder, there is only a check if the given parameter is not null. The mouse event is not null and therefore it goes in the suggest mode:
![image](https://cloud.githubusercontent.com/assets/24670532/21426950/14aa023c-c852-11e6-9ce4-e371bbb9d358.png)

Nice christmas holidays to all of you!
Alex

**Comment by Razoralpha** [comment]
I can reproduce this with Leaflet 1.2 and Geocoder 1.5.5 with Nominatim.
It only happens when "collapsed: true" is set.
