### ISSUE TITLE
Search box outside Map div

### ISSUE THREAD

**Issue by BasmaNabil** [perliedman/leaflet-control-geocoder#159]
Hello,

First of all thanks for this very useful plugin.
I have some questions:
I want to make the search box outside the map
I want to get the lat & long of the point after searching for it 
Can the marker be draggable?
Thanks in advance

**Comment by perliedman** [comment]
Hi,

1. the control isn't designed for this; it's a Leaflet control. You could probably do it by extracting relevant parts of the plugin, without too much work, but not something I've done
2. use the `markgeocode` event (https://github.com/perliedman/leaflet-control-geocoder#customizing), it contains the center coordinate in the event's `geocode.center` property
3. again, see [customization](https://github.com/perliedman/leaflet-control-geocoder#customizing), you can tailor how the geocoding result is shown any way you like; just add a marker with `draggable: true`

**Comment by NicoHood** [comment]
It would be really nice, if this plugin could pickup the search text from an external source.

**Comment by simon04** [comment]
See https://github.com/perliedman/leaflet-control-geocoder/pull/265 and https://github.com/perliedman/leaflet-control-geocoder/commit/66252f6c52ac90481590319bc8378dbd710eccee.
