### ISSUE TITLE
How to update popup after dragging the marker?

### ISSUE THREAD

**Issue by BasmaNabil** [perliedman/leaflet-control-geocoder#160]
I have a leaflet map where i am using leaflet-Control-Geocoder to get some locations on search,then i add the results coordinates on 2 input fields,also i added a popup for the search result,the problem is that when the marker is moved the popup doesn't update with the new place,how can this be done?

    Mmap = L.map('Modalmap').setView([8.7144, 125.7481],8);
		L.tileLayer( 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			attribution: '&copy; <a href="https://www.openstreetmap.org/copyright"></a>',
			subdomains: ['a','b','c']
		}).addTo(Mmap);
    var geocoder = L.Control.geocoder({
	        defaultMarkGeocode: false,
	        draggable:true
	    })
	    .on('markgeocode', function(e) {
	        var box = e.geocode.center;
	        var name=e.geocode.name;
	        document.getElementById("Latitude").value = box.lat;
	        document.getElementById("Longitude").value = box.lng;
	        MarkLayer=L.marker([box.lat,box.lng],{draggable:true}).addTo(Mmap). 
	        on('dragend', onDragEnd). 
    		bindPopup(e.geocode.name). 
    		openPopup(); 
    		displayLatLng(box); 

	        group = new L.featureGroup([MarkLayer]);

	        Mmap.fitBounds(group.getBounds());
	    }).addTo(Mmap); 

	    function onDragEnd(event) 
	    {
		    var latlng = event.target.getLatLng();

		    displayLatLng(latlng);
		}

		function displayLatLng(latlng) {
		    document.getElementById("Latitude").value = latlng.lat;
		    document.getElementById("Longitude").value = latlng.lng;
		}

**Comment by perliedman** [comment]
Hi,
this isn't really about Leaflet Control Geocoder but about how to implement certain use cases with Leaflet. You're better off asking on Stackoverflow or gis.stackexchange.com.
