### ISSUE TITLE
Can you build leaflet for meteor?

### ISSUE THREAD

**Issue by rikyperdana** [perliedman/leaflet-control-geocoder#162]
I need leaflet geocoder plugin for my meteor project
ianng:leaflet-control-geocoder has been abandoned since 2015
Unfortunately I had to use this package even if I has to downgrade my leaflet package to older version
Any way you can help me? ;(

**Comment by perliedman** [comment]
Hm, sorry, don't know anything about Meteor, and no idea what ianng:leaflet-control-geocoder is...

Happy to (try to) help with more concrete questions, don't think there's anything I can do about this right now.
