### ISSUE TITLE
Submit listener?

### ISSUE THREAD

**Issue by Dr-Mx** [perliedman/leaflet-control-geocoder#163]
Is it possible submit the default control by a method other than the ENTER key?
I see it could be done back in #70 through triggering a listener, but is this now obsolete?

In my limited wisdom I tried sending the following keydown event, but no luck.
`$('.leaflet-control-geocoder-form input').trigger($.Event('keydown', { which: $.ui.keyCode.ENTER, keyCode: $.ui.keyCode.ENTER }));`

Cheers

**Comment by perliedman** [comment]
Well, there's not really any "officially supported" ways to trigger a geocode externally, but in practice it's really easy. If you look at [what the code does when the user hits enter](https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/control.js#L261), you'll find that it starts the geocode by simply calling:

```
this._geocode();
```

You can do the same!

Note that it's not guaranteed to work in any future version of the plugin (methods prefixed with `_` indicate that they're private), but I have no plan of changing this any time soon!

**Comment by Michal0307** [comment]
It works, it would be good to implement this public method. I was looking for an option or method called on window load /startup to run searching.
