### ISSUE TITLE
Improvement: Add fire event when noResults are found

### ISSUE THREAD

**Issue by santiquetzal** [perliedman/leaflet-control-geocoder#165]
I need to override the default behaviour of noResults (display no result message).

In my use case if no results are found for a specific query I want to run another search with less search parameters, but this logic will be on my own project.

I don't know if this is allowed by the project right now, so... I'll made a fork of the proyect and add a noResults function and defaultNoResults option.

I'm new at github and I'm not sure how can I create a pull request, so... I leave my code here in case you want to merge: [v.1.5.4.b](https://github.com/santiquetzal/leaflet-control-geocoder/releases/tag/v1.5.4b)

**Comment by perliedman** [comment]
Hi and thanks for this!

I think I have two suggestions on how to best approach this:

* You could listen to the `finishgeocode` event and check if the results are empty and take appropriate action
* You could also make a geocoder class that delegates the actual calls to other geocoding classes, calling the in serial until one returns results:

```js
var SerialGeocoder = L.Class.extend({
    initialize: function(geocoders) {
        this.geocoders = geocoders;
    },
    geocode: function(query, cb, context) {
        var queue = this.geocoders.slice();
        var next = function(results) {
            if (results && results.length) {
                return cb.call(context, results);
            }
            var geocoder = queue.shift();
            if (geocoder) {
                return geocoder.geocode(query, next);
            }
            cb.call(context, []);
        };
        next();
    }
});
```

Note: I haven't run or even syntax checked the code above, take it as some kind of guidance.

**Comment by santiquetzal** [comment]
First of all thank you for your fast answer. 

Until your suggestion I had the code running with my new event and it works well. Although I prefer to change my code to use your version.

I'm trying to change the behaviour of my app to use the `finishgeocode`, but I have a problem: **I don't know how can I obtain the results** inside `.on('finishgeocode', function(result) {...} )`
If I print the result on Chrome debugger I obtain:
```javascript
Object {type: "finishgeocode", target: NewClass}
target:NewClass
type:"finishgeocode"
__proto__:Object
```
I have defined the geocoder as: 
```javascript
// I can have more than one map on the screen, so I define a geocoder for each of them
leafletData.getMap(vm.id).then(function(map) {
    geocoder = L.Control.geocoder({...<options>...})
    .on('markgeocode', function(e) {
        // Update coordintes, put a marker on the map and open the popup.
    }.on('finishegeocode', function(r) { 
        console.log(r);
    }).addTo(map)
}
```
To do the search I have to use a trick
- Fill HTML input via JS (because I have an address form in my app that must be fullfilled by the user)
- Call `geocoder._geocode();`

If I call `geocoder.options.geocoder.geocode(<query_string>, function (r){console.log(r)}, this);` the network request is done, but the event `finishgeocode` is not fired.

Thank you in advance

**Comment by perliedman** [comment]
Hm, weird. Looking at the code that fires `finishgeocode` (https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/control.js#L144), it definitely looks like the event should include a `results` property.

If you have the input in some other form, you're probably better off using the geocoder classes (`L.Control.Geocoder.Nominatim`, for example) directly, instead of going via the control.

Each geocoder class has a `geocode` method that you provide a `query` and `callback` argument to, an the `callback` will be called with the results. (See docs for details: https://github.com/perliedman/leaflet-control-geocoder#igeocoder)

**Comment by perliedman** [comment]
Ok, 1.5.5 was released quite a while ago, so I'm closing this.
