### ISSUE TITLE
L.Mixin.Events is deprecated

### ISSUE THREAD

**Issue by epotockiy** [perliedman/leaflet-control-geocoder#168]
L.Mixin.Events is deprecated in latest version of leaflet, could you update plugin to run with L.Evented instead?

**Comment by cccruzr** [comment]
Apparently, all you have to change is the line:
`includes: L.Mixin.Events,` 

with

 `includes: (L.Evented.prototype || L.Mixin.Events),`

**Comment by perliedman** [comment]
This should be fixed by ba481c9448ae58395e0ca60050189c974c790f65 and is now released as version 1.5.6.
