### ISSUE TITLE
npm: leaflet should be defined as a peer dependency

### ISSUE THREAD

**Issue by derwaldgeist** [perliedman/leaflet-control-geocoder#171]
It is obvious that the npm package requires leaflet as a peer dependency, but it is not defined in the `package.json` file.

**Comment by perliedman** [comment]
Hi, thanks for reporting.

While in theory, this makes a lot of sense, in practice this has lead to a lot of confusion and issues.

For example, this plugin works with Leaflet 0.7 as well as Leaflet 1.0+, but listing a peer dependency leads people to believe it can only be used with certain versions.

Also, I don't remember if it was with this plugin or one of my other Leaflet plugins, but once I listed Leaflet as a peer dependency, users started complaining about all sorts of build issues.

I've come to the conclusion that _not_ listing Leaflet as a peer dependency is the simplest; users tend to understand that they need Leaflet for it to work properly anyway.

**Comment by derwaldgeist** [comment]
Ok, makes pretty much sense.
