### ISSUE TITLE
Confusing example code

### ISSUE THREAD

**Issue by stevage** [perliedman/leaflet-control-geocoder#176]
Hi, just wanted to share my confusing experience trying to get this going, using the HERE Maps geocoder. There are quite a few places where there are two possibilities:

- `new L.Control.Geocoder` or just `L.Control.Geocoder`
- `new L.Control.Geocoder.here` or just `L.Control.Geocoder.here`
- `L.Control.Geocoder` or `L.Control.geocoder` (both defined, but seem to do different things)
- `L.Control.Geocoder.here` or `L.Control.Geocoder.HERE` (ditto)

There seems to be inconsistency between the documentation and demo code:

README:

> `new L.Control.Geocoder.Nominatim()`

Demo code:

> `'Nominatim': L.Control.Geocoder.nominatim(),`

README:

> `var geocoder = L.Control.geocoder`

Demo code:

> `control = new L.Control.Geocoder({ geocoder: null }),`

Anyway, the magic combination that worked for me in the end:

```
   var here= L.Control.Geocoder.here({
          app_id: '...',
          app_code: '...'
        });

    var geocoder = new L.Control.Geocoder({
        defaultMarkGeocode: false,
        geocoder: here
    })
```

**Comment by perliedman** [comment]
Hi and thanks for pointing this out.

I guess two things that could be made more clear here are:

* Like in Leaflet core, `new X()` as well as `x()` are equivalent; however, all code and examples should probably use the second form
* The difference between the geocoder _control_ (the user interface, the `L.Control.Geocoder` class) and the geocoder (code responsible for turning a query into a coordinate, usually by communicating with a backend) could be made clearer

**Comment by simon04** [comment]
For the reference, this is covered in the Leaflet docs: http://leafletjs.com/reference-1.2.0.html#class-class-factories
