### ISSUE TITLE
How to pass key to Google API?

### ISSUE THREAD

**Issue by nils-v** [perliedman/leaflet-control-geocoder#178]
Hi Per,

I tried to pass the API key to Google provider as follows:

```
var MapGeoCoderProvider = L.Control.Geocoder.google({
	key:			'<My API Key>'
});
var MapGeoCoder = L.Control.geocoder({
	position: 		'bottomright',
	placeholder: 	'Ort/Adresse...',
	errorMessage: 	'Nicht gefunden.',
	geocoder: 		MapGeoCoderProvider
}).addTo(Map);

```
but I could not find it in the request header.
How can I pass options to Google API?

Thanks
Nils

**Comment by perliedman** [comment]
Hi!

The key should be the first argument to the constructor, options the second. So like this:

```js
var MapGeoCoderProvider = L.Control.Geocoder.google('<you API key>', { ... other options ... });
```

The code in question, for reference: https://github.com/perliedman/leaflet-control-geocoder/blob/master/src/geocoders/google.js#L12
