### ISSUE TITLE
Drops a pin after clicking on a search result when collapsed option is false

### ISSUE THREAD

**Issue by wqoq** [perliedman/leaflet-control-geocoder#179]
For my project, I need the search bar always expanded (users weren't seeing the search button, or weren't recognizing its purpose), so I set `options.collapsed` to `false`.

I have a custom `markgeocode` handler which just calls `fitBounds` with the result's `bbox`, but I also have a completely separate event handler on the `click` event of the map which draws a special kind of marker. The simple demo at (http://www.liedman.net/leaflet-control-geocoder/) is a pretty close aproximation of what I'm trying to do, with minor differences.

Searching works great, until they use the mouse to click on one of the search results. This isn't a duplicate of #142, but I think it's happening as a result of the changes in #142.

Actually, I can recreate the same problem in the simple demo because there's a `click` handler on the map:

1. Set the `collapsed` option to `false`.
2. Search for some term that will return results.
3. Now press the mouse down on one of the results, **but don't release the mouse button**.
4. At this point, the result list closes, the map pans/zooms to its location, and the default markgeocode handler does its thing.
5. Now release the mouse button. It drops a marker where you released the mouse. (Edit: Assuming you're hovering over somewhere where reverse geocode works.)

I suppose what's happening here is, because the result list is gone, you're now triggering a `mouseup` event on the map, and somewhere in the bowels of Leaflet that becomes a `click` event, and so on.

This doesn't happen when `collapsed` is true, because the result list stays open on `mousedown`, and it can stop the propagation of the event.

Edit: I should also say I'm doing this in Chrome, in case that matters.

**Comment by wqoq** [comment]
I created PR #181 that fixes this. Turned out to be quite easy once I really understood what #142 was doing.

**Comment by simon04** [comment]
Fixed via fc30c23/#181.
