### ISSUE TITLE
Uncollapsed mode: Geocoding is triggered for an empty input

### ISSUE THREAD

**Issue by dmolineus** [perliedman/leaflet-control-geocoder#194]
When using the geocode control in the uncollapsed mode the geocoding is triggered just right after the first click in the control.

I think it was introduced at this line in the following commit https://github.com/perliedman/leaflet-control-geocoder/commit/f528ff13cc1fb1bb71c0c9aaa0ffd8340a129679#diff-cb2640e0bae61c7ddd5681b932941f66R92

The behaviour is irritating because a user get the error message "no result" before trying to enter anything. This doesn't happen in the collapsed mode.

It would be nice if a min length setting would be added so this issue could be avoided.

**Comment by maxenz** [comment]
+1

**Comment by perliedman** [comment]
Really long turn around time for this one, but hopefully fixed now. Added the option `queryMinLength` which defaults to `1`, so you have to type at least one characters to trigger geocoding.

**Comment by dmolineus** [comment]
@perliedman Is there anything I could do to support you for a new release?
