### ISSUE TITLE
Multiple osm_tag to filter Photon result

### ISSUE THREAD

**Issue by marcus-at-localhorst** [perliedman/leaflet-control-geocoder#196]
Hi,
it's possible to add multiple `osm_tag` parameter to filter photon results for `osm_key` and `osm_value` fields. https://github.com/komoot/photon/blob/master/README.md#user-content-filter-results-by-tags-and-values

To filter all shops from the result set I would do this. 

```js
M.geocoder = L.Control.geocoder({
	geocoder: L.Control.Geocoder.photon({
		geocodingQueryParams: {
			limit: 8,
			osm_tag: '!shop'
		}
	})
})
```
Which translate to: `https://photon.komoot.de/api/?q=kaufland&limit=8&osm_tag=!shop`

But of course it is not possible to have multiple `osm_tag` params
`https://photon.komoot.de/api/?q=kaufland&limit=8&osm_tag=!shop&osm_tag=!landuse`
 since same keys are getting merged:

```js
geocodingQueryParams: {
	osm_tag: '!shop',
	osm_tag: '!landuse',
}
```
And when I look at the utils/getJSON function I don't see how to make this work with only changing the Photon provider plugin.

Any idea?

**Comment by simon04** [comment]
Specifying two identical keys for the JavaScript object cannot work, since the second one overrides the first one. An option would be to specify an array of `osm_tag`, but this function https://github.com/Leaflet/Leaflet/blob/6708981c7474109211162103037b28c26724ed51/src/core/Util.js#L145-L156 does not handle arrays.

```
geocodingQueryParams: {
	osm_tag: ['!shop', '!landuse']
}
```

We could either file a PR for Leaflet, or copy & modify this function in leaflet-control-geocoder.

**Comment by marcus-at-localhorst** [comment]
I think photon is not really standard conform here. The right way to do it is `osm_tag[]=x&osm_tag[]=y` so in this case this hack should be made in the leaflet-control-geocoder lib. I'm not really familiar with the build process of this lib, else I would have give it a shot. Maybe I'll try it.

**Comment by marcus-at-localhorst** [comment]
What if params can be also a string and the query gets build in the provider plugin for this special case?
```js
export function getJSON(url, params, callback) {
 //...
   if (typeof params === 'object') {
        url + L.Util.getParamString(params);
    }else{
       url += params;
    }
  xmlHttp.open('GET', url, true);
 // ...
}
```

**Comment by simon04** [comment]
Since 2d06ebf, the following should work and yield the URL `...&osm_tag=!shop&osm_tag=!landuse`:

```js
geocodingQueryParams: {
	osm_tag: ['!shop', '!landuse']
}
```
