### ISSUE TITLE
A few words on diversity in tech

### ISSUE THREAD

**Issue by zopyx** [perliedman/leaflet-control-geocoder#197]
Is it really necessary to put this into a repository? At the top of a README file? I am all with you. Being gay myself but this really does not belong at the top of a repository.

**Comment by perliedman** [comment]
I highly doubt you're all with me on this: if you were, I don't think you would have taken the time to open this issue. It's completely optional to read it, it is completely optional to use this repository.

As to your question, is it really necessary? Yes, I definitively think so, that's sort of the message of the whole text. The current situation is absurd, and I think pointing this out, in a perhaps unexpected place, is the least I can do. You're of course completely fine to disagree.
