### ISSUE TITLE
Custom input

### ISSUE THREAD

**Issue by suyalcinkaya** [perliedman/leaflet-control-geocoder#198]
Hi,

Thanks for the repo. It helped me a lot. But I couldn't figure how to access search from custom input? Using angularjs 1.6.9.

**Comment by perliedman** [comment]
Hi, great that you find it useful.

Not entirely sure what you mean. Do you have your own input, and just want to perform the search?

**Comment by suyalcinkaya** [comment]
I would like to perform search from outside of the map. Example;

```html
<input ng-model="query" />
<button ng-click=performSearch(query)></button>
```

After search I need the get results as well.

**Comment by perliedman** [comment]
You can use the geocoder classes directly for that.

Something like:

```js

$scope.performSearch = function(query) {
    var geocoder = new L.Control.Geocoder.Nominatim();
    geocoder.query(query, function(results) { $scope.results = results; });
}
```

You can then use your scope's `results` to show them.

**Comment by suyalcinkaya** [comment]
Getting error as;

```js
TypeError: geocoder.query is not a function
```

**Comment by suyalcinkaya** [comment]
Nevermindi I didn't see that you updated
```js
geocoder.query(query, function(results) { $scope.results = results; });
```
as
```js
geocoder.geocode(query, function(results) { $scope.results = results; });
```

Now it works. Thanks a lot 👍
