### ISSUE TITLE
How to set a zoom level when moved to searched location?

### ISSUE THREAD

**Issue by idenchev** [perliedman/leaflet-control-geocoder#201]
Hello,

I am wondering how can I customize the zoom level when the screen is changed to the searched location? Currently all my searches are shown with zoom of 5 km. Is there an option to keep the current zoom?

Thank you!

**Comment by perliedman** [comment]
Hi! It sounds like you've found the solution. Except for what you already said, you can also completely customize how the geocoded location is handled, and set any zoom level you want, etc. See the [customization section](https://github.com/perliedman/leaflet-control-geocoder#customizing) in the docs.

I'm closing this for now!
