### ISSUE TITLE
L is undefined on import

### ISSUE THREAD

**Issue by GillesVandewiele** [perliedman/leaflet-control-geocoder#206]
Hey guys,

I have been getting the following error when starting my application. The error gets resolved by removing the leaflet-control-geocoder import...

```
Control.Geocoder.js:901 Uncaught TypeError: Cannot read property 'Class' of undefined
    at Object.<anonymous> (Control.Geocoder.js:901)
    at Object.9.../util (Control.Geocoder.js:992)
    at s (Control.Geocoder.js:1)
    at Control.Geocoder.js:1
    at Object.<anonymous> (Control.Geocoder.js:4)
    at Object.1../geocoders/nominatim (Control.Geocoder.js:307)
    at s (Control.Geocoder.js:1)
    at Control.Geocoder.js:1
    at Object.<anonymous> (Control.Geocoder.js:1168)
    at Object.12../control (Control.Geocoder.js:1208)
```

**Comment by GillesVandewiele** [comment]
Seems I included a bit too much in my gitignore. Starting from a fresh slate and minimizing it made everything work.

**Comment by azyth** [comment]
@GillesVandewiele Hey, I am getting the exact same error with a fresh install and no modifications to my .gitignore, what was your actual problem? it seems to function properly even with the error occurring.

**Comment by azyth** [comment]
Note: I am using Ionic 3 
Appears that i can get it to go away by moving the `<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>` script tag down into body, in index.html. instead of in `<head>` where I had it before.

**Comment by GillesVandewiele** [comment]
Tbh, I kind of forgot what I did in order to make it work. But you got it working right now?

I think I had a lot in my .gitignore file. Currently, I have:
```
/dist
/tmp
/out-tsc
/node_modules
/.idea
.project
.classpath
.c9/
*.launch
.settings/
*.sublime-workspace
/www
.sourcemaps
```

And it is working :)
