### ISSUE TITLE
Craft a 1.6.0 release?

### ISSUE THREAD

**Issue by simon04** [perliedman/leaflet-control-geocoder#207]
Hi, since we accumulated quite some bug fixes and improvements [since the last 1.5.8 release](https://github.com/perliedman/leaflet-control-geocoder/compare/v1.5.8...master@%7B2018-07-20%7D), let's bring out a 1.6.0 release. This brings those fixes out and shows that this project is still actively maintained. Thank you! :smile:

**Comment by perliedman** [comment]
Sorry, I've been a on a quite long vacation, but this sounds like a good idea! :+1:

**Comment by perliedman** [comment]
Closed by 0f6e66f5b64c6a74fcedb384e6670bf0360f41b0 :smiley:
