### ISSUE TITLE
GitHub: detach the fork

### ISSUE THREAD

**Issue by simon04** [perliedman/leaflet-control-geocoder#218]
If you agree with this suggestion, please write to the GitHub support https://github.com/contact

> The project `perliedman/leaflet-control-geocoder` has outpaced the one it forked from, so would you please remove the "forked from" link (detach the fork)?

**Comment by perliedman** [comment]
Good idea, I have contemplated this at several points, but never gotten around to it.

**Comment by perliedman** [comment]
Support request has been sent.

**Comment by perliedman** [comment]
Done!
