### ISSUE TITLE
[BUG] with IE 8 / 9 / 10 --> SOLVED !!

### ISSUE THREAD

**Issue by Captain-FLAM** [perliedman/leaflet-control-geocoder#221]
After hours of search on the web and debugging in my browsers (FF & IE 9 for testing purpose only), I add my two cents ...
As I don't want to fork all the project, I just post my working solution there !

Replace :

```
function getJSON(url, params, callback) {
	var xmlHttp;
	// For IE8-9-10
	if(window.XDomainRequest)
	{
		xmlHttp = new XDomainRequest();
		
		xmlHttp.open('get', url + getParamString(params));
		xmlHttp.onerror = function () { callback(''); return; };
		xmlHttp.onload = function() { callback(JSON.parse(xmlHttp.responseText)) };
		setTimeout(function () { xmlHttp.send(); }, 0);
	}
	// ************************************** //
	else
	{
		xmlHttp = new XMLHttpRequest();
```

P.S : Thanks for the good job you're doing :1st_place_medal:

**Comment by simon04** [comment]
Thanks for sharing. `XMLHttpRequest` should be supported down to IE7 according to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_compatibility

**Comment by perliedman** [comment]
I think the issue might be that in some older versions of IE (7, as far as I understand), `XMLHttpRequest` don't support CORS, but you can work around it with `XDomainRequest`.

Not entirely against supporting IE7 if it's not more intrusive than the code above, but that browser has reached EOL a long time ago and a major part of the web must be broken when using it already. If this is important to you, at least open a PR.

**Comment by Captain-FLAM** [comment]
I don't know why, but it was not working on my IE 9 (even on 8 mode)
