### ISSUE TITLE
Searching on a lat-lon combination does not return the correct location

### ISSUE THREAD

**Issue by MaartenDeen** [perliedman/leaflet-control-geocoder#222]
I'm not very at all familiar in how searching works in leaflet-control-geocoder, but when filing a [bug](https://github.com/nrenner/brouter-web/issues/134#issuecomment-430730562) with brouter that uses it for searching it seems it is a bug here.

When you search for a lat-lon combination, apparently leaflet-control-geocoder returns the center of the nearest way. That can result in large offsets between the point you are looking for and what is returned. E.g. 51.681605, 11.1441273 which brouter/leaflet-control-geocoder returns as http://brouter.de/brouter-web/#map=16/51.6756/11.1383/OpenStreetMap but which is actually https://www.openstreetmap.org/search?query=51.681605%2C%2011.1441273%20#map=19/51.68160/11.14413
The distance is about 800 meters by road. IMHO searching for a lat-lon combination should always return that exact location.

![brouter](https://user-images.githubusercontent.com/1825970/47110201-7790e000-d250-11e8-9ac2-6b72e9c43b6e.png)

![osm](https://user-images.githubusercontent.com/1825970/47110220-7e1f5780-d250-11e8-9d89-0739ffa231de.png)

**Comment by perliedman** [comment]
Hi,
thanks for reporting!

The fact is that leaflet-control-geocoder does not have any built-in handling on lat/lng coordinate input, so it is simply displaying what the backend geocoding service (in this case presumably Nominatim) responds with to such a query.

That is, in my view this is not a problem with the control, but dependent on the underlying service. brouter could presumably create a geocoding service that works like what OpenStreetMap use, and it would work with leaflet-control-geocoder. I do not think this is something we should special case in the control.
