### ISSUE TITLE
Version 1.6 on NPM not reflecting change

### ISSUE THREAD

**Issue by marcus-at-localhorst** [perliedman/leaflet-control-geocoder#223]
Hi,

I wanted to check out this change: https://github.com/perliedman/leaflet-control-geocoder/commit/2d06ebf665882f3241bd9f4c035762282ce399c9 but the dist version on npm doesn't reflect that change. https://unpkg.com/leaflet-control-geocoder@1.6.0/dist/Control.Geocoder.js

e.g. `url + getParamString(params)` is still `url + L.Util.getParamString(params)`

Do I miss something?

**Comment by perliedman** [comment]
Hi, yes that is unfortunately expected since the 1.6.0 is too old to include that fix. We will have to make a new release.
