### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by MiXT4PE** [perliedman/leaflet-control-geocoder#225]
I load these scripts in my head:

     <script src="js/jquery.min.js" defer></script>
     <script src="https://unpkg.com/leaflet@latest/dist/leaflet.js" defer></script> 
     <script src="https://unpkg.com/leaflet-control-geocoder@latest/dist/Control.Geocoder.js"></script>
     <script src="js/siteworks.js" defer></script>

I create a map which is displayed correctly and when I add the geocoder `L.Control.geocoder().addTo(map);` I get this error:

`Uncaught TypeError: Cannot read property 'extend' of undefined
    at nominatim.js:5
    at index.js:42`

nominatim.js:

    import L from 'leaflet';
    import { template, getJSON } from '../util';

    export default {
      class: L.Class.extend({          <--
        options: {
        .
        .
        .

**Comment by googlsux** [comment]
This has nothing to do with the other scripts eg. siteworks.  Even a minimal HTML that does nothing shows this error after load in Chrome console:

<!DOCTYPE html>
<html>
    <head>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@latest/dist/leaflet.css" />
	<link rel="stylesheet" href="Control.Geocoder.css" />
	<script src="Control.Geocoder.js"></script>
	<script src="https://unpkg.com/leaflet@latest/dist/leaflet-src.js"></script>
    </head>
    <body>
    </body>
</html>

Result: 

nominatim.js:5 Uncaught TypeError: Cannot read property 'extend' of undefined
    at nominatim.js:5
    at index.js:42

Very unprofessional, what is the source of this problem??

**Comment by perliedman** [comment]
@googlsux yeah, in you're case, you are loading the scripts in the wrong order. The geocoder needs to load after Leaflet. I suspect a similar problem in the first case: `L.Class.extend` is a function in Leaflet, it's not something that this plugin has invented.

Please submit a running example of the issue if you still think this is an issue.

@googlsux also if you think this plugin is unprofessional, please just don't use it and never ever write to me again. I do this for free and owe you exactly zero. You and comments like that are why I rarely bother to maintain open source any more.

**Comment by MiXT4PE** [comment]
@perliedman You closed my issue and only replied to this random guy who commented. I loaded the scripts in the correct order.

**Comment by madvik** [comment]
I have the same issue. Have you found the source of the problem?

**Comment by leonheess** [comment]
@madvik Sorry, I was never able to solve this problem and decided to switch to a different library as Mister Liedman decided to close my issue while only replying to another comment and not to my initial issue nor my follow-up question. This just signals to me that this library is likely not really supported anymore so I moved on.

**Comment by simon04** [comment]
> Please submit a running example of the issue if you still think this is an issue.

No one did.

> Try adding that.

No one addressed this issue or replied to it.

----

Here is a small example that runs without problems: https://github.com/perliedman/leaflet-control-geocoder/tree/master/demo-unpkg

**Comment by madvik** [comment]
I think solved the problem.
In first time I try to do this :
```
<script type='text/javascript' src='http://dev1.local/wp/wp-content/mu-plugins/wordpress/lib/leaflet/leaflet.js?ver=5.4.1'></script>
<script type='text/javascript' src='http://dev1.local/wp/wp-content/mu-plugins/wordpress/lib/leaflet-geocoder/esri-leaflet-geocoder.js?ver=5.4.1'></script>
```

After I see an another lib to load: esri-leaflet.js
```
<script type='text/javascript' src='http://dev1.local/wp/wp-content/mu-plugins/wordpress/lib/leaflet/leaflet.js?ver=5.4.1'></script>
<script type='text/javascript' src='http://dev1.local/wp/wp-content/mu-plugins/wordpress/lib/leaflet-esri/esri-leaflet.js?ver=5.4.1'></script>
<script type='text/javascript' src='http://dev1.local/wp/wp-content/mu-plugins/wordpress/lib/leaflet-geocoder/esri-leaflet-geocoder.js?ver=5.4.1'></script>
```

**Comment by leonheess** [comment]
@madvik Just fyi the `type`-attribute is deprecated and should be omitted (:

**Comment by madvik** [comment]
@leonheess It is automatic in WordPress. ;-)

**Comment by perliedman** [comment]
@leonheess Yeah, sorry about closing it abruptly, but if you read my response, it says:

> I suspect a similar problem in the first case: `L.Class.extend` is a function in Leaflet, it's not something that this plugin has invented.

And I stand by the important part: without a reproducible, running example, it is usually impossible as a maintainer to find out what is happening. A few `<script>` tags and an error message is rarely enough, unless it's a problem you have seen before.
