### ISSUE TITLE
Add button to add a marker

### ISSUE THREAD

**Issue by Garito** [perliedman/leaflet-control-geocoder#229]
Hi!
I've been playing with the demo and I've noticed that when you double click on the map to zoom in a marker is added which is annoying

Is it possible to add a second button below the search one to activate/deactivate the marker insertion? (if so: how?)

Thanks

**Comment by perliedman** [comment]
The marker is added by the map click listener in the demo. It is not part of the plugin, just for showing how the reverse geocoder works.

Just remove the click listener if you don't like it.
