### ISSUE TITLE
defaultMarkGeocode: false does not allow the geocoder to function

### ISSUE THREAD

**Issue by cbeddow** [perliedman/leaflet-control-geocoder#230]
I want to be able to search for a location, then zoom to it, but not have a blue marker on the map once I've arrived there.

My code:

`L.Control.geocoder({ expand: 'click',  }).addTo(map);`

This works ^ -- but when I try to disable the marker:

`L.Control.geocoder({ expand: 'click',  defaultMarkGeocode: false }).addTo(map);`

Now I can search, click my desired location in the dropdown but the map does not zoom to the location.

**Comment by DGrv** [comment]
I had the same issue and found an example how to do it on [map2gpx](https://github.com/tmuguet/map2gpx), at [this code](https://github.com/tmuguet/map2gpx/blob/8068e2c4d999bbe8111a75cc3c8577d43a160147/src/js/controls.js#L116), here what I used:

    L.Control.geocoder({ 
      position: 'topleft',
      expand: 'click',
      defaultMarkGeocode: false
    }).on('markgeocode', function(e) { 
      map.setView(e.geocode.center, 11
    ); }).addTo(map);
