### ISSUE TITLE
Django-leaflet caveat: include geocoder JS after {% leaflet_js %}

### ISSUE THREAD

**Issue by florianm** [perliedman/leaflet-control-geocoder#234]
Users of django-leaflet need to include the geocoder JS *after* the django-leaflet JS. \
As trivial as this sounds, this is easy to overlook with a moderately complex template inheritance structure.

e.g. my form's js block:
```
{% block extrajs %}
{% leaflet_js plugins="ALL" %}
{{ form.media.js }}
{% include 'shared/map.js' %}
{% endblock extrajs %}
```

`map.js`:
```
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
<script type="text/javascript">
  window.addEventListener("map:init", function (event) {
    var map = event.detail.map;
    {% include 'shared/overlays.html' %}
    map.addControl(new L.Control.Fullscreen());
    map.addControl(new L.Control.Geocoder());
});
</script>
```
Where (not related to this issue) `overlays.html` contains a few additional WMS overlays.

Thanks for a fantastic plugin that "just works"!

**Comment by perliedman** [comment]
:+1:
