### ISSUE TITLE
[Bug] Add control geocoder into map google layer (this.on is not function)

### ISSUE THREAD

**Issue by hieuhn280292** [perliedman/leaflet-control-geocoder#238]
Hi!
I have an issues and i need help, pls.
I am using Leaflet Control Geocoder package with google layer map and leaflet version:  0.7
i have contexmenu:
![image](https://user-images.githubusercontent.com/50007000/56791626-b58b4400-6831-11e9-84b5-d1031df438d5.png)
and "View address" call function:
![image](https://user-images.githubusercontent.com/50007000/56791703-eec3b400-6831-11e9-91e0-99db4e2b9403.png)
But it throw issues:
![image](https://user-images.githubusercontent.com/50007000/56791775-1a469e80-6832-11e9-8bb9-f41efc3d230a.png)
Can you help me pls. Thanks in advance!

**Comment by perliedman** [comment]
Hard to tell without at least a stacktrace or preferably a running example.

I would remove the two instantiated controls, since it does not look like you are using them anyway.
