### ISSUE TITLE
Docs for webpack and mapbox

### ISSUE THREAD

**Issue by timgp** [perliedman/leaflet-control-geocoder#245]
I have Leaflet up and running in my webpack project, but I'm not sure how best to add the control, specifically with Mapbox. Can you offer any advice please? 

Happy to PR the docs when I understand it.

**Comment by simon04** [comment]
This snipped should work:

```js
import L from 'leaflet';
import 'leaflet-control-geocoder';

var map = L.map('map');
L.Control.geocoder().addTo(map);
```

**Comment by timgp** [comment]
Thanks Simon, working
