### ISSUE TITLE
L is undefined

### ISSUE THREAD

**Issue by jessypouliot98** [perliedman/leaflet-control-geocoder#248]
Error Code:
> ./src/vendors/leaflet-control-geocoder/dist/Control.Geocoder.js
>   Line 1483:  'L' is not defined  no-undef`

My JavaScript File

`import L from 'leaflet';`
**`import '../../../vendors/leaflet-control-geocoder';`** //Error here
`import 'leaflet-routing-machine';`

`class MapsWidget{`
`...`
`}`

I'm trying to import this and I get the above error. Anyone knows how I can fix this or if this is normal ? I'm using React.js

**Comment by simon04** [comment]
Please consult one of the demos: https://github.com/perliedman/leaflet-control-geocoder#demos
