### ISSUE TITLE
"Nominatim.class is not a constructor" on v.1.3.1 and v.1.8.0

### ISSUE THREAD

**Issue by ethmz** [perliedman/leaflet-control-geocoder#249]
I noticed that the "Nominatim.class is not a constructor" error is back again in Leaflet Control Geocoder 1.8.0, with Leaflet v.1.3.1

The error is also showing on the demo: https://www.liedman.net/leaflet-control-geocoder/

**Comment by ZachPerkitny** [comment]
@ethmz Same problem, it broke production this morning :(

**Comment by Willven** [comment]
Seems to be a case of changing `new Nominatim.class()` to `new Nominatim()` within `Control.js`?

This being said, I'm not an expert in Javascript or anywhere familiar enough with this repo to feel qualified to make the change.

**Comment by simon04** [comment]
Sorry for the inconvenience caused. The problem occurred when relying on the default geocoder. I hopefully addressed the issue with v1.8.2, https://www.npmjs.com/package/leaflet-control-geocoder/v/1.8.2

The demo should start working within a few minutes, once unpkg.com delivers the new version.
