### ISSUE TITLE
showResultIcons NOT WORKING

### ISSUE THREAD

**Issue by niichuu** [perliedman/leaflet-control-geocoder#251]
Hello and thanks for reading,

Im traing to configure my geocoder and showResultIcons is not working.
Maybe im not codding well.

I'll be thankfull if u help me!

![image](https://user-images.githubusercontent.com/47673538/59606127-b8463f00-90e6-11e9-95b5-c2e953ce54a7.png)

**Comment by perliedman** [comment]
Setting `showResultIcons` to false should disable them. If you want icons, set the option to true instead.

**Comment by niichuu** [comment]
That's my issue
I do not want the icons, but setting false it still showing it.

**Comment by perliedman** [comment]
Must be something else, the icons are off (`false`) by default, so you should not have to disable them. You can check the demo, which uses the Nominatim geocoder and does not show icons.

If the problem persists, please try to make an example that we can that illustrates the issue.

**Comment by niichuu** [comment]
Thanks for the prompt response.
I'll check it and give u back a feedback
