### ISSUE TITLE
[Ask/Suggest] When not found result and osm_type

### ISSUE THREAD

**Issue by mujieniwa** [perliedman/leaflet-control-geocoder#266]
Hi, good day.

First, this is a very good plugin, thanks for making it.
Second:
- I want to ask what if the search results are not found then query post / http post into the internal database?
- osm_type has several types, such as nodes, ways and relations, while the plugin only shows the "icon" node, the name of the road does not indicate "way polygon", is there another way to manipulate it?

Thank you very much,
Regards,
M

**Comment by perliedman** [comment]
Hi and sorry about a late reply!

* First question: not entirely sure what you are asking here?
* As for other properties from the Nominatim geocoder: each geocoding result has `properties` which contain all the original information as returned by Nominatim, you can hopefully find what you need there.
