### ISSUE TITLE
Release archive does not contain dist/Control.Geocoder.js

### ISSUE THREAD

**Issue by hakan42** [perliedman/leaflet-control-geocoder#285]
The archive seems to be just the source tree zipped. This makes using the geocoder impossible to use as a webjar ( https://www.webjars.org/ )

Many other leaflet plugins are packages in such a way that the release contains dist/css, dist/js, and can be automatically converted into webjars and used in spring boot applications.

**Comment by simon04** [comment]
The compile file is part of the npm release:

```
$ curl --silent https://registry.npmjs.org/leaflet-control-geocoder/-/leaflet-control-geocoder-1.13.0.tgz | tar --list --gzip | grep dist
package/dist/Control.Geocoder.css
package/dist/images/throbber.gif
package/dist/Control.Geocoder.js
package/dist/Control.Geocoder.min.js
package/dist/Control.Geocoder.js.map
package/dist/Control.Geocoder.min.js.map
package/dist/images/geocoder.png
```

**Comment by hakan42** [comment]
ah, o.k., thank you.

found the archive at https://repo1.maven.org/maven2/org/webjars/npm/leaflet-control-geocoder/
