### ISSUE TITLE
Not clear how to use this geocoder with Mapbox

### ISSUE THREAD

**Issue by mpgr04** [perliedman/leaflet-control-geocoder#287]
I have been trying to add a geocoder with Mapbox as provider for quite some time now - but without success.
I try to add the Geocoder as follows:

L.Control.Geocoder.mapbox("token").addTo(mapInstance);

This call results in the following error message:
Uncaught TypeError: L.Control.Geocoder.mapbox(...).addTo is not a function

But if I add the Geocoder with its standard values, i.e. the standard provider, this is no problem.
It would be great if someone could explain how to use this Geocoder with Mapbox.

**Comment by simon04** [comment]
The way to go is
```js
L.Control.geocoder({
  geocoder: L.Control.Geocoder.mapbox(…)
}).addTo(…);
```

Please see https://github.com/perliedman/leaflet-control-geocoder#lcontrolgeocoder and https://github.com/perliedman/leaflet-control-geocoder/blob/master/demo/index.html

**Comment by mpgr04** [comment]
Thanks for pointing me in the right direction!

**Comment by isahua16** [comment]
Hello mpgr04! Did you end up figuring out how to make it work with mapbox? I am also having issues getting this working.
