### ISSUE TITLE
Overwriting the "markgeocode" event not possible in TypeScript

### ISSUE THREAD

**Issue by mpgr04** [perliedman/leaflet-control-geocoder#320]
Currently I'm using this library with TypeScript, which has worked fine so far. But now I have encountered the problem that I am not able to override the "markgeocode" event.

I proceeded as described in the API docs, also I set the defaultMarkGeocode property to false.

But in TypeScript I get the following error:

 Argument of type '"markgeocode"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.

**Comment by simon04** [comment]
Would you mind sharing a small example how to reproduce this error, please? You might want to start with the demo from https://github.com/perliedman/leaflet-control-geocoder/blob/master/demo/index.html – Thanks!

**Comment by mpgr04** [comment]
I have now tried several things and found that it works fine in normal JS, even in TypeScript if the GeoCoder is converted to any type beforehand. 

The problem can also be avoided by implementing a separate property using declaration merging.

**Comment by mpgr04** [comment]
Hi, quick update, the problem has certainly settled!

Blame was a stupidly named variable which did not point to the real control but to the map, now everything works.

Sorry for wasting your time!
