### ISSUE TITLE
[URGENT ON ASAP basis] Please update the license as LGPL (commercial usage issues)

### ISSUE THREAD

**Issue by vissharm** [perliedman/leaflet-control-geocoder#325]
It would be great if you can update the license under LGPL. The nomination geocodes service (https://github.com/osm-search/Nominatim) is licensed under GPLv2, so even if we use the BSD2 licensed package/library to access GPLv2 package library API's, it would require commercial applications to convert to GPLv2. Hence I wouldn't be able to use leaflet-control-geocoder too. This has been verified by me with the license verification department and the code scanner tool we use. I would request you to update the license as LGPL.

**Comment by vissharm** [comment]
@perliedman Please look at it on priority basis.

**Comment by perliedman** [comment]
Not sure what you want here, the library is released under BSD license, which is a lot more permissive than LGPL, in my understanding. Also, the fact that Nominatim's _code_ is GPLv2 does not mean that using their API is under the same license. IANAL, but I would assume use of Nominatim's API is under the same license as the rest of OpenStreetMap's database.

Any way, I have a hard time seeing any benefit from releasing this library under another license.
