### ISSUE TITLE
any way to get the 'addresstags' from the OSM/Nominatim API results ?

### ISSUE THREAD

**Issue by analoghifi** [perliedman/leaflet-control-geocoder#350]
Is there any way to get the 'addresstags' elements from the OSM/Nominatim API results ?
especially 'suburb' is important for me
example result:
https://[nominatim.openstreetmap.org/details.php?osmtype=W&osmid=475448638&class=building&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=475448638&class=building&addressdetails=1&hierarchy=0&group_hierarchy=1&format=json)

there is some 'suburb' variable in 'NominatimAddress' here (nominatim.ts line 42):
https://github.com/perliedman/leaflet-control-geocoder/blob/be056ab13910c94639338268f0c5b6cdade01083/src/geocoders/nominatim.ts#L42
but when acessing via result.address.suburb it return always 'undefined'
(other elements of 'NominatimAddress' I can access without any problems 
e.g.   result.address.house_number, result.address.postcode and result.address.state)

**Comment by BlackBrix** [comment]
additional clarification: 
especially 'addr:suburb' and 'addr:hamlet' would be important for me
