### ISSUE TITLE
geocodingQueryParams to specify the city?

### ISSUE THREAD

**Issue by rossanag** [perliedman/leaflet-control-geocoder#40]
I am using  L.Control.Geocoder.nominatim, although it finds the name of the street within the proper country it misses some street cities (not listed), specially  the one I am living in (the biggest one). I tryed with and without the 'city' parameter. I have idea how to name/use all the possible parameters.

    geocoder: L.Control.Geocoder.nominatim({
        geocodingQueryParams: { countrycodes: 'uy', city: 'Montevideo' }  
    
    // didn't work, so I left only the codecountries: 'uy' option

Thanks!

**Comment by p4535992** [comment]
Hi Rossanag, i have the same trouble, may I ask if you are getting your own solution to share and what service are you used?

**Comment by perliedman** [comment]
Feel free to continue this discussion, but I'm closing the ticket, since it's not an issue that will be fixed in this plugin.

**Comment by p4535992** [comment]
I'm really sorry, I wrote the comment without thinking that was within
a tab of the issue .


2015-11-03 12:44 GMT+01:00 Per Liedman <notifications@github.com>:
