### ISSUE TITLE
Use events

### ISSUE THREAD

**Issue by perliedman** [perliedman/leaflet-control-geocoder#42]
Add events for when:

* geocoding starts
* results are received
* result is shown on the map
* an error occurs

**Comment by AW-UC** [comment]
Yeah, this is really missing. I am using your Routing Machine and it's `getWaypoints()` on `routesfound`. Sometimes, the names of the waypoints are resolved, sometimes not. Would be much better to call that method again on `geocodingDone` event.

**Comment by perliedman** [comment]
For the case with Leaflet Routing Machine, I don't this would help, since the plan is to add events to the control class, which LRM does not use.

In your scenario, I would create a new geocoder class that is just a wrapper around the geocoder you're using today. In the wrapper, you can intercept the callback from the real geocoder, and do whatever you need to do if there are no results.

```
var Wrapper = L.Class.extend({
    initialize: function(geocoder) {
        this._geocoder = geocoder;
    },

    geocode: function(query, cb, context) {
        this._geocoder(query, function(results) {
            if (!results || results.length === 0) {
                // No results found!
            }
            cb.call(results, context);
        });
    }
});
```

(I haven't actually run the code above, but it should give you the idea.)

**Comment by AW-UC** [comment]
@perliedman thanks, this goes in the direction of what I am already doing right now.
