### ISSUE TITLE
Problems using plugin when in a div not on the map

### ISSUE THREAD

**Issue by ruggerscottso** [perliedman/leaflet-control-geocoder#50]
I've added the pluging to a modal div instead of being directly on the map.  When I search for a location, the search is performed correctly (see firebug output in attached "notworking" image), but I do not get a selection list when multiple results are retruned, like in the demo (attached "working" image).  I intend to use the results of the geocoder to programmatically zoom/center my map to the location, but need to handle cases where multiple locations are returned.  Do you have any suggestions for my issue in this use case?

![geocode-working](https://cloud.githubusercontent.com/assets/11094280/6305958/3fba15fe-b8fd-11e4-8c97-59f4fad96f64.png)
![geocode-notworking](https://cloud.githubusercontent.com/assets/11094280/6305953/38504c98-b8fd-11e4-8361-9e3d8ca32944.png)

**Comment by perliedman** [comment]
The code for displaying the result is pretty hardwired to working as a Leaflet control. Can't say for certain, but it's pretty likely that you will run into weird issues like this if you place the control in another container.

For this scenario, I think you might be better off just using the classes that communicate with the backend, and write your own UI to show the results (for example, you could look at using [Awesomeplete](http://leaverou.github.io/awesomplete/)).

You can use `L.Control.Geocoder.Nominatim` directly, for example, and just call the `geocode` method with your query. I use this method myself in some other projects, like [Leaflet Routing Machine](https://github.com/perliedman/leaflet-routing-machine), that reuse the geocoding servces implementations.
