### ISSUE TITLE
using leaflet-control-geocoded on gridlayers

### ISSUE THREAD

**Issue by jbaddnz** [perliedman/leaflet-control-geocoder#52]
Hi,

I'm wanting to use reverse geocoding on a map and pull data from a grid layer to integrate with the popup message.

I currently use this code to access map box Grid layers:
vfrbiGrid.on('click', function(e) {
    if (!e.data) return;
    var popup = L.popup({
    keepInView: true,
    closeOnClick: true
    })
        .setLatLng(e.latLng)
        .setContent(''Site Name: ' + e.data.site_desc + '<br>'  + 'Site lat: ' + e.data.lat + '<br>' + 'Site long: ' + e.data.long)        
        .addTo(map);
   }); 

where vfrbiGrid is:
var vfrbiGrid = L.mapbox.gridLayer('jamiebaddeley.VF_RBI_Coverage').addTo(map),

That all works well.

What I want to do though is use your code instead as I'd get reverse geocoding results as well.

I tried this:
------
vfrbiGrid.on('click', function(e) {
                         geocoder.reverse(e.latlng, map.options.crs.scale(map.getZoom()), function(results) {
                                var r = results[0];
                                if (r) {
                                        if (marker) {
                                                marker.
                                                        setLatLng(r.center).
                                                        setPopupContent(r.html || r.name).
                                                        openPopup();
                                        } else {
                                                marker = L.marker(r.center)
                                                		.bindPopup(r.name)
                                                		.addTo(map)
                                                		.openPopup();
                                        }
                                }
                        })
			})
------
But I get an error in the console:

[Error] TypeError: undefined is not an object (evaluating 'location.lat')
	reverse (Control.Geocoder.js, line 702)
	(anonymous function) (vfrbi2, line 214)
	fireEvent (mapbox.js, line 1)
	(anonymous function) (mapbox.js, line 6)
	(anonymous function) (mapbox.js, line 1)
	(anonymous function) (mapbox.js, line 6)
	_getTile (mapbox.js, line 6)
	getData (mapbox.js, line 6)
	_click (mapbox.js, line 6)
	fireEvent (mapbox.js, line 1)
	_fireMouseEvent (mapbox.js, line 1)
	_onMouseClick (mapbox.js, line 1)
	o (mapbox.js, line 3)

-----

it works fine when I make it map.on('click', function(e) {
but that doesn't mean I have access to the data held in the grid that I want to pull from and add to in the popup.

Can you help me please?

thanks

jamie

**Comment by perliedman** [comment]
It looks like the `e.latlng` you're passing in to the `reverse` method doesn't contain a `lat` property. It might be that the grid layer (which I'm not familiar with) just passes an array - Leaflet uses arrays and `L.LatLng` object interchangeably, but some parts of the geocoder plugin obviously does not.

A workaround could be to change the first lines of your code to:

```js
vfrbiGrid.on('click', function(e) {
geocoder.reverse(L.latLng(e.latlng), map.options.crs.scale(map.getZoom()), function(results) {

[...]
```

Hope this helps!

**Comment by jbaddnz** [comment]
Thanks so much. It wasn't actually that but when your workaround didn't
work it caused me to focus on that particular area of the code. It turns
out that is was a case issue i.e e.latLng rather than e.latlng that made it
work!

Next step from here is trying to make the popup stay active until another
click. It's a rather a large amount of data I'm now filling the popup with
including hyperlinks so moving the mouse up to them.

Kindest Regards, and thanks again,

jamie

**Comment by perliedman** [comment]
Nice that it worked out! Thanks.
