### ISSUE TITLE
Search doesn't display anything

### ISSUE THREAD

**Issue by piratenpanda** [perliedman/leaflet-control-geocoder#54]
I'm using everything as written in the Readme. The search field opens and when entering a name and pressing enter the throbber appears. Yet no results are displayed and the throbber is just turning endlessly. This is 1.1.0 using leaflet 0.7.2

**Comment by perliedman** [comment]
Does the javascript console show any error? Check the debugger to see if it makes any requests. What query are you making?

Does the example code in the `demo` directory work? Does the example on the plugin's page (http://www.liedman.net/leaflet-control-geocoder/) work?

Need some more details to work with!

**Comment by piratenpanda** [comment]
Forgot to say, no javascript erros. Demo page works fine, that's why I'm wondering.

**Comment by piratenpanda** [comment]
Just searching for cities, didn't change anything in the code

**Comment by piratenpanda** [comment]
Ah, the demo.html inside the 1.1.0 release also doesn't work. Yet the online demo works just fine.

**Comment by perliedman** [comment]
That is indeed odd. I'm running it fine here. 

Are you running from a real web server (not loading from file://) when this happens? The control, by default, does not work unless you're using HTTP or HTTPS.

What browser/OS are you on?

**Comment by piratenpanda** [comment]
Ah that's the problem obviously. I'm trying out some changes to my map locally. I'll upload it to my server and try again. Thank you

**Comment by piratenpanda** [comment]
ok, works fine. Sorry for the trouble

**Comment by perliedman** [comment]
Since quite several AJAX things break when running from `file://`, I've grown accustomed to using for example https://www.npmjs.com/package/http-server instead. Very easy to start from the command line, making it as easy as `file://`, but it works as a real server. Saves a lot of time compared to copying to a remote server!
