### ISSUE TITLE
How just to get geocodeResult by string query?

### ISSUE THREAD

**Issue by meliborn** [perliedman/leaflet-control-geocoder#58]
Can't find it in readme. I have a query string (Moscow, Mavra street, 18 for example). How can I send geocode request? 
I tried ```L.Control.Geocoder.Nominatim({q: 'Moscow, Mavra street, 18'})``` but nothing happened

**Comment by perliedman** [comment]
Try it like this:

```js
var geocoder = L.Control.Geocoder.nominatim();

geocoder.query('Moscow, Mavra street, 18', function(results) {
    console.log(results);
});
```

Note that the `query` function is asynchronous, so you'll get the result in the callback, not in the function's returned value.

**Comment by meliborn** [comment]
Got ``` geocoder.query is not a function```

**Comment by meliborn** [comment]
Replaced ```query``` with ```geocode```, seems ok.

**Comment by perliedman** [comment]
Oops, yes, sorry, trying to type out of my memory rather than actually checking the code.
