### ISSUE TITLE
MapRequest geocoder

### ISSUE THREAD

**Issue by kegita** [perliedman/leaflet-control-geocoder#60]
Can you write,please, the code i should use with mapRequest? I have tried but the input don't get back any result.

**Comment by perliedman** [comment]
Assuming you have a valid MapQuest API key (you have to register for one), and a Leaflet map setup in a variable called `map`, use the code below, and insert your API key:

```
L.Control.geocoder({
    geocoder: L.Control.Geocoder.mapQuest('replace with your MapQuest API key here')
}).addTo(map)
```

Hope this helps!
