### ISSUE TITLE
reverse geocoder on hybrid apps won't work

### ISSUE THREAD

**Issue by Herb-sh** [perliedman/leaflet-control-geocoder#68]
I'd like start by saying thanks for your work, i really like it.
Leaflet control geocoder jsonp call urls don't start with a web protocol(http/https) in desktop browsers this won't cause any issue but if you are building hybrid apps with local assets the protocol used will be "file://" and so jsonp calls will fail. Using a protocol at the beggining of url-s will solve the problem

**Comment by perliedman** [comment]
Yes, this is a known issue for environments that don't handle protocol relative urls (#30).

Set `serviceUrl` for the geocoder to work around it if necessary.
