### ISSUE TITLE
trigger form submit (_geocode) from own ui element

### ISSUE THREAD

**Issue by marteb** [perliedman/leaflet-control-geocoder#70]
I would like to add my own ui element (like a button) to submit the geocoder form.

In your code, there is an event listener which triggers the _geocode method on form submit:

    L.DomEvent.addListener(form, 'submit', this._geocode, this);

But how can i submit the geocode form from my own button without editing your code?

I edited your code and added:

    L.DomEvent.addListener('.geocode-trigger-button', 'click', this._geocode, this);

and it works, but i don’t want to add it to your code due to version control and updatability reasons.

**Comment by perliedman** [comment]
Actually not sure, but if you really want to, I guess you could look up the right element and just add a submit button element, using `appendChild` or some jQuery, if you prefer that. Like you say, there's already a submit listener, so it's just a matter of getting the button to show up in the right place.

Of course, this is a bit of a hack, and most likely the layout will break, so you'll have to fix the CSS after doing this.

Any particular reason you need this button? It could be an option for the control, if it's a general use case.

**Comment by marteb** [comment]
I need this because i want to show the input field initially and exchange the search icon (which normally just opens the input field) with a search button, with which the user can trigger the search as well as with hitting the enter key.

**Comment by marteb** [comment]
Appending a submit button works fine, thanks!

**Comment by perliedman** [comment]
Ha! Yes, thought about making the search icon into a button just now. I'll think of that as a future feature.
