### ISSUE TITLE
Option to enable/disable to create marker easly

### ISSUE THREAD

**Issue by SilentT-FR** [perliedman/leaflet-control-geocoder#71]
markGeocode: function(result) {
			this._map.fitBounds(result.bbox);
[IF OPTION ]
			if (this._geocodeMarker) {
				this._map.removeLayer(this._geocodeMarker);
			}

			this._geocodeMarker = new L.Marker(result.center)
				.bindPopup(result.html || result.name)
				.addTo(this._map)
				.openPopup();
[ENDIF]
			return this;
		},

all in the title

**Comment by HarelM** [comment]
I have decided to allow the user to remove the marker with double click:
below is the relevant code, feel free to use it :-)

```js
markGeocode: function(result) {
			this._map.fitBounds(result.bbox);

			if (this._geocodeMarker) {
				this._map.removeLayer(this._geocodeMarker);
			}
			this._geocodeMarker = new L.Marker(result.center)
				.bindPopup(result.html || result.name)
				.addTo(this._map)
				.openPopup();
			var _this = this;
			this._geocodeMarker.once("dblclick", function () {
			    _this._map.removeLayer(_this._geocodeMarker);
			    _this._geocodeMarker = null;
		    });

			return this;
		},
```

**Comment by perliedman** [comment]
In 3863759694094787184dd04798eb6ab5f9791eea, events where introduced to make customization easier.

The exact way a geocode should be marked can undoubtedly vary in a million ways, so no need to add options etc. Instead, you can now disable the default marker behaviour, which is there to make it really easy to get started, and add your own custom marker logic by listening to an event:

Like in the readme:

```javascript
var geocoder = L.Control.geocoder({
        defaultMarkGeocode: false
    })
    .on('markgeocode', function(e) {
        var bbox = e.geocode.bbox;
        var poly = L.polygon([
             bbox.getSouthEast(),
             bbox.getNorthEast(),
             bbox.getNorthWest(),
             bbox.getSouthWest()
        ]).addTo(map);
        map.fitBounds(poly.getBounds());
    })
    .addTo(map);
```
