### ISSUE TITLE
Don't put input in a form

### ISSUE THREAD

**Issue by domialex** [perliedman/leaflet-control-geocoder#86]
Putting the input in a form prevents the map from being inside a form. (Not HTML compliant)
In my case, I made the form a simple div container and removed the listener:
```javascript
//L.DomEvent.addListener(form, 'submit', this._geocode, this);
```
I also made the input a type search, it allows to clear the field with the escape key. Then I made the escape key clear the results below the field.
```javascript
// Escape
case 27:
   this._clearResults();
   if (this.options.collapsed) {
	this._collapse();
   }
break;
```
I also needed to make the enter key make a query.
```javascript
// Enter
case 13:
	L.DomEvent.preventDefault(e);				
	if (this._selection) {
		var index = parseInt(this._selection.getAttribute('data-result-index'), 10);
		this._geocodeResultSelected(this._results[index]);
		this._clearResults();
	}
	else
	    this._geocode(e);
}
```

**Comment by nobodyman** [comment]
Ran into this issue as well, with a twist.  If the form in question utilizes the JQuery Validate plugin,  the browser throws a TypeError exception whenever the geocoder control gains/loses focus.
