### ISSUE TITLE
L.Control.Geocoder.Nominatim() `options` argument broken

### ISSUE THREAD

**Issue by n4nn31355** [perliedman/leaflet-control-geocoder#92]
Unfortunately `L.Control.Geocoder.Nominatim()` doesn't read `options`.

For example following code doesn't work:
```javascript
var geocoder = L.Control.geocoder({
    geocoder: L.Control.Geocoder.Nominatim({
        geocodingQueryParams: {countrycodes: 'ru'}
    })
}).addTo(map);
```

**Comment by perliedman** [comment]
You should either use `new`, like:

    new L.Control.Geocoder.Nominatim({
        geocodingQueryParams: {countrycodes: 'ru'}
    })

or the factory method (notice initial lower case):

    L.Control.Geocoder.nominatim({
        geocodingQueryParams: {countrycodes: 'ru'}
    })

Does this help?

**Comment by n4nn31355** [comment]
Yep, it's fine with `new`.
Thanks!
