### ISSUE TITLE
reverse/ create redirect

### ISSUE THREAD

**Issue by ENDiGo** [perliedman/leaflet-control-geocoder#95]
Please change this line
``` javascript
Util.jsonp(this.options.serviceUrl + 'reverse/', L.extend({
```
to
``` javascript
Util.jsonp(this.options.serviceUrl + 'reverse', L.extend({
```

**Comment by perliedman** [comment]
Is this for the Nominatim geocoder, or which part of the code are we talking about?

**Comment by perliedman** [comment]
Also, could you explain why you need this change?

**Comment by ENDiGo** [comment]
It's inside in geocoders/nominatim.js. Line number 63.

If i didn't change this line, request returned 301 Moved Permanently and creates new request.

![untitled-1](https://cloud.githubusercontent.com/assets/1501644/10509515/2404f978-7360-11e5-928e-4f3742ec2e90.jpg)

**Comment by perliedman** [comment]
Ok! Thanks for noticing.

I'll fix this.

**Comment by perliedman** [comment]
Interesting to note that this redirect doesn't happen on the public Nominatim service. However, removing the slash works equally well, so all is good.

Thanks!

**Comment by ENDiGo** [comment]
Thanks good.
