### ISSUE TITLE
Missing images in bower.json?

### ISSUE THREAD

**Issue by restani** [perliedman/leaflet-control-geocoder#98]
I'm quite new to bower, so maybe I'm wrong.

I'm using your plugin with meteor (loaded with bower using mquandalle:bower).

I'm having an issue where the images are not displayed on the control. I tried adding them to the "main" section of the bower.json file, to have them bundled and they appear.

Am I misunderstanding something or should the bower.json file's main section be more like:

    "main": [
        "Control.Geocoder.js",
        "Control.geocoder.css",
        "images/geocoder.png",
        "images/throbber.gif"
    ]

?

**Comment by perliedman** [comment]
I actually do not know! I don't use Bower, and never have, so my knowledge is very limited. The `bower.json` in the repo was contributed by someone else.

Any help is very welcome!

**Comment by restani** [comment]
Looking at leaflet's bower.json file, it looks like they have the images in the main section:

    "main": [
        "dist/leaflet.css",
        "dist/leaflet-src.js",
        "dist/images/layers-2x.png",
        "dist/images/layers.png",
        "dist/images/marker-icon-2x.png",
        "dist/images/marker-icon.png",
        "dist/images/marker-shadow.png"
    ]


So I guess it's not wrong to put them here. Mind if I open a PR for that?

**Comment by perliedman** [comment]
@restani sounds great!

**Comment by restani** [comment]
Done !
